(module
  (func $inc (param $a i32) (result i32)
    (local.get $a)
    (i32.const 1)
    (i32.add)
  )
  (export "inc" (func $inc))
  (func $main (result i32)
    (i32.const 2)
    (call $inc)
    (i32.const 3)
    (i32.add)
  )
  (export "main" (func $main))
)